### ISSUE TITLE
Copyright question

### ISSUE THREAD

**Issue by merksk8** [bradvin/dashicons-picker#7]
Hello!

I'm preparing a plugin totally free for Wordpress Directory, can I use this library??

I can give credits in it if you want it, I found it really usefull and this plugin will be always open source and free to everyone, but anyway I prefeer to ask before publishing it.

Thanks for your time and great job !

**Comment by technofreaky** [comment]
Hi,

This script is a open source . which means you can use it and if you like you can give credit to the developer
for more info please check this (https://github.com/bradvin/dashicons-picker/blob/master/LICENSE)

**Comment by merksk8** [comment]
Ok, thanks then! I will use it and give credits :)

One tip, i had troubles to add functions when selecting an icon, and add an event to it on line 302.:

`$( document ).trigger( "iconSelected", [ button.data('target'), icons[i] ] );`

Probably is not the best way, not the best function and can have troubles but it's just an idea to  add an event to attach functions when selecting icons, sending to the event the target id and the icon id.

Thanks for all!!

**Comment by technofreaky** [comment]
@merksk8  i am not much good at javascript. so i think @bradvin must take a look at it.

**Comment by bradvin** [comment]
@merksk8 this is licensed under the GPL, and you can give credit if you want to, or not :)
