### ISSUE TITLE
Not working in with Wordpress 5.6

### ISSUE THREAD

**Issue by ChonPaSa** [bradvin/dashicons-picker#9]
After migrating to 5.6 the picker shows no icons

![image](https://user-images.githubusercontent.com/39958735/104008523-d7fdf600-51a9-11eb-999d-46989d6d7193.png)

Nothing in the console. Most likely something to do with jQuery but I couldn't figure it out yet

**Comment by bradvin** [comment]
Ye I tested it and it also does not work for me. 
This lib needs to be updated to work with jQuery 3

**Comment by ChonPaSa** [comment]
I downgraded wp jquery from 3.5.1 to 3.1.1 and it works there. Trying to see what changed since 3.1.1

**Comment by bradvin** [comment]
I made a small change to the JS - download the latest and test that out. It works for me now

**Comment by ChonPaSa** [comment]
It works. Brilliant. Thank you for your work!!
